jupyter 연습

In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data, y_data 준비

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

placeholder 생성

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

variables 생성

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

expression, cost function, train

In [6]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

session 생성하고 run

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11407.703 
Prediction:
 [63.916138 65.81676  70.42296  78.04809  46.316566]
10 Cost:  34.956184 
Prediction:
 [158.23204 179.21907 182.1386  199.7054  132.82286]
20 Cost:  34.673935 
Prediction:
 [158.4955  179.57722 182.46996 200.06802 133.10493]
30 Cost:  34.496758 
Prediction:
 [158.47446 179.59335 182.46434 200.06367 133.12605]
40 Cost:  34.320503 
Prediction:
 [158.45264 179.6084  182.45775 200.05823 133.14636]
50 Cost:  34.14513 
Prediction:
 [158.43083 179.6234  182.45116 200.05281 133.16661]
60 Cost:  33.970768 
Prediction:
 [158.40913 179.63838 182.44461 200.04741 133.18681]
70 Cost:  33.79736 
Prediction:
 [158.38745 179.65329 182.43805 200.04199 133.20692]
80 Cost:  33.624947 
Prediction:
 [158.36586 179.66815 182.4315  200.03662 133.227  ]
90 Cost:  33.453346 
Prediction:
 [158.34431 179.68298 182.42499 200.03123 133.24704]
100 Cost:  33.282753 
Prediction:
 [158.32283 179.69778 182.41849 200.02588 133.267  ]
110 Cost:  33.11306 
Prediction:
 [158.3014  179.71254 1

 [156.7134  180.80663 181.93239 199.61948 134.7684 ]
950 Cost:  21.678305 
Prediction:
 [156.6964  180.81837 181.92728 199.61513 134.78433]
960 Cost:  21.570957 
Prediction:
 [156.67944 180.83006 181.92216 199.6108  134.80023]
970 Cost:  21.46412 
Prediction:
 [156.66252 180.84174 181.91707 199.60646 134.81609]
980 Cost:  21.357838 
Prediction:
 [156.64565 180.85338 181.91197 199.60213 134.8319 ]
990 Cost:  21.252264 
Prediction:
 [156.62883 180.86496 181.90689 199.59781 134.84764]
1000 Cost:  21.147196 
Prediction:
 [156.61206 180.87653 181.90184 199.59352 134.86337]
1010 Cost:  21.042713 
Prediction:
 [156.59532 180.88805 181.89679 199.5892  134.87903]
1020 Cost:  20.9387 
Prediction:
 [156.57863 180.89955 181.89175 199.58493 134.89468]
1030 Cost:  20.835321 
Prediction:
 [156.562   180.91103 181.88675 199.58066 134.91028]
1040 Cost:  20.73248 
Prediction:
 [156.5454  180.92247 181.88174 199.5764  134.92583]
1050 Cost:  20.63023 
Prediction:
 [156.52887 180.93388 181.87677 199.57216 

1910 Cost:  13.60396 
Prediction:
 [155.26369 181.80675 181.49614 199.24211 136.13301]
1920 Cost:  13.53981 
Prediction:
 [155.25066 181.81572 181.49223 199.23865 136.14534]
1930 Cost:  13.476056 
Prediction:
 [155.23769 181.82468 181.48833 199.2352  136.15762]
1940 Cost:  13.412607 
Prediction:
 [155.22475 181.83363 181.48445 199.23178 136.16989]
1950 Cost:  13.349487 
Prediction:
 [155.21185 181.84256 181.48059 199.22835 136.18213]
1960 Cost:  13.286715 
Prediction:
 [155.19896 181.85143 181.4767  199.2249  136.1943 ]
1970 Cost:  13.22431 
Prediction:
 [155.18613 181.86029 181.47285 199.2215  136.20647]
1980 Cost:  13.162191 
Prediction:
 [155.17331 181.86911 181.469   199.21808 136.2186 ]
1990 Cost:  13.100431 
Prediction:
 [155.16057 181.87794 181.46518 199.21468 136.2307 ]
2000 Cost:  13.039034 
Prediction:
 [155.14784 181.88673 181.46138 199.2113  136.24277]
